repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
    -   id: black
    -   id: black-jupyter
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
