exclude: python_tools/utils/proto/.*
repos:
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.1.0
    hooks:
      - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
# -   repo: https://github.com/sqlfluff/sqlfluff
#     rev: 3.0.7
#     hooks:
#     -   id: sqlfluff-lint
#         args: [--dialect, sqlite] # , --exclude-rules, CP02]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
    -   id: markdownlint-fix
        files: '.*\.md'
        args: [--disable, MD013]
