repos:
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
-   repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
# -   repo: https://github.com/sqlfluff/sqlfluff
#     rev: 3.0.7
#     hooks:
#     -   id: sqlfluff-fix
#         files: '.*\.sql'
#         args: [--dialect, sqlite, --exclude-rules, CP02]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
    -   id: markdownlint-fix
        files: '.*\.md'
        args: [--disable, MD013]
