# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keys.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nkeys.proto\x12\x12mixxx.track.io.key"\xa4\x02\n\x06KeyMap\x12=\n\nglobal_key\x18\x01 \x01(\x0e\x32 .mixxx.track.io.key.ChromaticKey:\x07INVALID\x12\x17\n\x0fglobal_key_text\x18\x02 \x01(\t\x12\x38\n\nkey_change\x18\x03 \x03(\x0b\x32$.mixxx.track.io.key.KeyMap.KeyChange\x12\x34\n\x06source\x18\x04 \x01(\x0e\x32\x1a.mixxx.track.io.key.Source:\x08\x41NALYZER\x1aR\n\tKeyChange\x12\x16\n\x0e\x66rame_position\x18\x01 \x01(\x05\x12-\n\x03key\x18\x02 \x01(\x0e\x32 .mixxx.track.io.key.ChromaticKey*3\n\x06Source\x12\x0c\n\x08\x41NALYZER\x10\x00\x12\x11\n\rFILE_METADATA\x10\x01\x12\x08\n\x04USER\x10\x02*\x89\x03\n\x0c\x43hromaticKey\x12\x0b\n\x07INVALID\x10\x00\x12\x0b\n\x07\x43_MAJOR\x10\x01\x12\x10\n\x0c\x44_FLAT_MAJOR\x10\x02\x12\x0b\n\x07\x44_MAJOR\x10\x03\x12\x10\n\x0c\x45_FLAT_MAJOR\x10\x04\x12\x0b\n\x07\x45_MAJOR\x10\x05\x12\x0b\n\x07\x46_MAJOR\x10\x06\x12\x11\n\rF_SHARP_MAJOR\x10\x07\x12\x0b\n\x07G_MAJOR\x10\x08\x12\x10\n\x0c\x41_FLAT_MAJOR\x10\t\x12\x0b\n\x07\x41_MAJOR\x10\n\x12\x10\n\x0c\x42_FLAT_MAJOR\x10\x0b\x12\x0b\n\x07\x42_MAJOR\x10\x0c\x12\x0b\n\x07\x43_MINOR\x10\r\x12\x11\n\rC_SHARP_MINOR\x10\x0e\x12\x0b\n\x07\x44_MINOR\x10\x0f\x12\x10\n\x0c\x45_FLAT_MINOR\x10\x10\x12\x0b\n\x07\x45_MINOR\x10\x11\x12\x0b\n\x07\x46_MINOR\x10\x12\x12\x11\n\rF_SHARP_MINOR\x10\x13\x12\x0b\n\x07G_MINOR\x10\x14\x12\x11\n\rG_SHARP_MINOR\x10\x15\x12\x0b\n\x07\x41_MINOR\x10\x16\x12\x10\n\x0c\x42_FLAT_MINOR\x10\x17\x12\x0b\n\x07\x42_MINOR\x10\x18\x42\x02H\x03'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "keys_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"H\003"
    _SOURCE._serialized_start = 329  # type:ignore
    _SOURCE._serialized_end = 380  # type:ignore
    _CHROMATICKEY._serialized_start = 383  # type:ignore
    _CHROMATICKEY._serialized_end = 776  # type:ignore
    _KEYMAP._serialized_start = 35  # type:ignore
    _KEYMAP._serialized_end = 327  # type:ignore
    _KEYMAP_KEYCHANGE._serialized_start = 245  # type:ignore
    _KEYMAP_KEYCHANGE._serialized_end = 327  # type:ignore
# @@protoc_insertion_point(module_scope)
